[general]
src_code_rel_path = "src"
distribution_rel_path = "dist"
blender_version = "4.3.0"
blender_backwards_compatible_version = "4.1.1"

[addon]
auto_launch_operator_id = "bpy.ops.wm.blender_dev_bridge"

[build]
build_legacy_addon_format = true
include_dependency_wheels = true
