schema_version = "1.0.0"

id = "vit_dt_blender_asset_downloader"
version = "0.6.0"
name = "ASIN Downlader"
tagline = "Download asset models from Woodshop or other Amazon sources"
maintainer = "Yongqing Ye <yongye@amazon.com>"
type = "add-on"
website = "https://code.amazon.com/packages/VitDtBlenderAssetDownloader/trees/mainline"
tags = ["Modeling"]
blender_version_min = "4.2.0"
license = ["GPL"]
platforms = ["windows-x64"]
