schema_version = "1.0.0"

id = "blender_dev_bridge"
version = "0.6.0"
name = "Blender Dev Bridge"
tagline = "An all-in-one Blender addon designed to streamline development workflows with tools for source code management, remote debugging, and enhanced developer productivity."
maintainer = "Yongqing Ye <avatar.ye@gmail.com>"
type = "add-on"
tags = ["Development"]
blender_version_min = "4.2.0"
license = ["GPL"]
platforms = ["windows-x64", "macos-arm64", "macos-x64", "linux-x64"]
