schema_version = "1.0.0"

id = "blender_dev_bridge"
version = "0.6.0"
name = "Blender Dev Bridge"
tagline = "An all-in-one tool set for Blender addon development"
maintainer = "Yongqing Ye <avatar.ye@gmail.com>"
type = "add-on"
tags = ["Development"]
blender_version_min = "4.2.0"
license = ["GPL"]
